name: Addon Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  addon-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push
        run: |
          python addons_xml_generator3.py
          git config --local user.email "ci@wolfietech.xyz"
          git config --local user.name "WolfieTech-CI"
          git add . || :
          git commit -m '[bot] Packaging addons and updating addons.xml' || :
          git push || :